{{- if (eq .Values.existingConfigMap "") }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "secretsync-events.configMapName" . }}
  labels:
    {{- include "secretsync-events.labels" . | nindent 4 }}
data:
  config.yaml: |
  {{- .Values.config | toYaml | nindent 4 }}
{{- end }}