apiVersion: v2
name: vault-secret-sync
description: A Helm chart for Kubernetes
type: application
version: 0.2.2
appVersion: "0.2.2"

dependencies:
  - name: vault-secret-sync-events
    version: 0.1.0
    condition: vault-secret-sync-events.enabled
  - name: vault-secret-sync-operator
    version: 0.1.0
    condition: vault-secret-sync-operator.enabled