---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "secretsync.configMapName" . }}
  labels:
    {{- include "secretsync.labels" . | nindent 4 }}
data:
  config.yaml: |
  {{- .Values.config | toYaml | nindent 4 }}
